# Generated by Django 4.1.4 on 2022-12-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='country',
            new_name='country_code',
        ),
    ]
